In [98]:
class LinearRegression:
    
    def __init__(self, epsilon=1e-4, max_iter=220, alpha=1e-2, momentum=1e-4):
        # HyperParams
        self.epsilon = epsilon
        self.max_iter = max_iter
        self.alpha = alpha
        self.momentum = momentum
        
        # Weights
        self.w = None
        
        
    def __calc_gradient(self, X, y):
        print("WEIGHTS", self.w, type(self.w))
        return  (2 * ((X.T).dot(X.dot(self.w) - y)))/len(self.w)
    
    
    def fit(self, X_train, y_train):
        w_shape = X_train.shape[1]
        self.w = np.ones(w_shape)
        w_current = np.zeros(w_shape)
        gradient = np.zeros(w_shape)
        for i in range(self.max_iter):
            momentum = self.momentum * gradient
            gradient = momentum + self.alpha * self.__calc_gradient(X_train, y_train)
            print(gradient)
            if np.linalg.norm(self.w - w_current) >= self.epsilon:
                w_current = self.w.copy()
                self.w = w_current - gradient
            else:
                break
        return self
    
    
    def predict(self, X_test):
        return X_test.dot(self.w)

In [86]:
path = 'homework-practice-03-data.csv'

In [87]:
import pandas as pd

/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [88]:
data = pd.read_csv(path)

In [89]:
data.head()

f0    f1        f2        f3        f4        f5           f6
0  16.99  1.01  0.976270 -3.697815  0.623295  0.524760  7199.992000
1  10.34  1.66  4.303787  7.715073  0.886961  0.473862  2466.136700
2  21.01  3.50  2.055268 -6.464284  0.618826  1.657394  2969.369100
3  23.68  3.31  0.897664  1.335254  0.133461  1.234554  1040.665300
4  24.59  3.61 -1.526904 -0.196414  0.980580  3.086397    37.469975

In [90]:
y = data['f1']
X = data.drop(['f1'], axis=1)

In [99]:
model = LinearRegression()
print(model.w)
fitted = model.fit(np.array(X), np.array(y))
fitted.w
# predictions = fitted.predict(X)

None
WEIGHTS [1. 1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
[ 1.36216164e+05 -2.15837532e+03  6.29449521e+03  2.82379862e+03
  7.34118242e+03  5.99081541e+08]
WEIGHTS [-1.36215164e+05  2.15937532e+03 -6.29349521e+03 -2.82279862e+03
 -7.34018242e+03 -5.99081540e+08] <class 'numpy.ndarray'>
[-8.13992046e+13  1.30874412e+12 -3.76449407e+12 -1.68739054e+12
 -4.38865705e+12 -3.58821424e+17]
WEIGHTS [ 8.13992045e+13 -1.30874412e+12  3.76449406e+12  1.68739054e+12
  4.38865704e+12  3.58821423e+17] <class 'numpy.ndarray'>
[ 4.87542620e+22 -7.83875645e+20  2.25475336e+21  1.01066688e+21
  2.62859738e+21  2.14917011e+26]
WEIGHTS [-4.87542619e+22  7.83875644e+20 -2.25475336e+21 -1.01066688e+21
 -2.62859737e+21 -2.14917010e+26] <class 'numpy.ndarray'>
[-2.92014901e+31  4.69504325e+29 -1.35049030e+30 -6.05341518e+29
 -1.57440513e+30 -1.28725094e+35]
WEIGHTS [ 2.92014900e+31 -4.69504324e+29  1.35049030e+30  6.05341517e+29
  1.57440513e+30  1.28725094e+35] <class 'numpy.ndarray'>
[ 1.74903073e+40 -2.812

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:26: RuntimeWarning: invalid value encountered in add


array([inf, nan, nan, inf, inf, nan])

In [66]:
X = boston['data']
y = boston['target']
w = np.ones(X.shape[1])
def __calc_gradient(X, y):
        return  (2 * ((X.T).dot(X.dot(w) - y)))/len(w)
    
print(__calc_gradient(X, y))

[3.09803632e+05 7.07335372e+05 8.33121891e+05 4.73732987e+03
 3.93296260e+04 4.31701099e+05 4.94675489e+06 2.48451332e+05
 7.57450683e+05 3.03402494e+07 1.28942517e+06 2.46550428e+07
 9.25664009e+05]


In [ ]:
test_calc = __calc_gradient() 

In [28]:
import numpy as np

In [10]:
from sklearn.datasets import load_boston

In [16]:
boston = load_boston()

In [24]:
X = boston['data']
y = boston['target']
columns = boston['feature_names']

In [23]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [20]:
type(X)

numpy.ndarray

In [21]:
X.shape

(506, 13)

In [22]:
y.shape

(506,)

In [79]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [25]:
columns

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [44]:
model = LinearRegression()
fitted = model.fit(X, y)
predictions = fitted.predict(X)
fitted.w

In [45]:
fitted.w

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])