## Библиотеки для анализа данных

### NumPy

Во всех заданиях данного раздела НЕЛЬЗЯ использовать циклы и list comprehensions. Под вектором и матрицей в данных заданиях понимается одномерный и двумерный numpy.array соответственно.

In [2]:
import numpy as np

**1. ** Реализуй функцию, возвращающую максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой. Для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответом является 5. Если нулевых элементов нет, функция должна возвращать None.


In [76]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

def max_element(arr):
    mask = (arr == 0) # [True if x == 0 else False for x in arr]
    result = (arr[1:])[mask[:-1]]
    if result.shape[0] != 0:
        return result.max()

print(max_element(x))

5


In [78]:
[True if x == 0 else False for x in np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])]

[False, False, True, False, True, True, False, False, True]

**2. ** Реализуй функцию, принимающую на вход матрицу и некоторое число и возвращающую ближайший к числу элемент матрицы. Например: для X = np.arange(0,10).reshape((2, 5)) и v = 3.6 ответом будет 4.

In [97]:
X = np.arange(0,10).reshape((5,2))
v = -133.6 #ответом будет 4.
def nearest_value(arr, value):
    return min((abs(arr-value).min()) + value, arr.max())
    
print(nearest_value(X, v))
print(X)

0.0
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**3. ** Реализуй функцию scale(X), которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает выборочное среднее и делит на стандартное отклонение). Убедись, что в функции не будет происходить деления на ноль. Протестируй на случайной матрице (для её генерации можно использовать, например, функцию [numpy.random.randint](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html)).

In [120]:
X = np.random.randint(0,10,(3,3))
X

array([[2, 7, 1],
       [0, 8, 8],
       [2, 7, 7]])

In [127]:
def scale(arr):
    mean = arr.mean(axis=0)
    std = arr.std(axis=0)
    mask = (std == 0)
    if True not in mask:
        return (arr - mean) / std
    else:
        return -1
            

print(scale(X))

[[ 0.70710678 -0.70710678 -1.40182605]
 [-1.41421356  1.41421356  0.86266219]
 [ 0.70710678 -0.70710678  0.53916387]]


In [117]:
scale(X)

array([4.33333333, 2.66666667, 4.        ])

**4. ** Реализуй функцию, которая для заданной матрицы находит:
 - след:  сумма элементов на диагонали
 - наименьший и наибольший элементы 

Для тестирования сгенерируй матрицу с элементами из нормального распределения $\mathcal{N}$(10,1)

In [133]:
X = np.random.randint(0,10,(3,3))

def get_stats(X):
    t = np.trace(X)
    return t, X.min(), X.max()

print(X)
print(get_stats(X))

[[7 2 3]
 [9 1 1]
 [1 8 5]]
(13, 1, 9)


**5. ** Повтори 100 раз следующий эксперимент: сгенерируй две матрицы размера 10×10 из стандартного нормального распределения $\mathcal{N}$(0,1), перемножьте их (как матрицы - посмотри в вики, что такое матричное умножение) и найди максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

In [147]:
def mul_matrix_n_max(matrix_1, matrix_2):
    multiplied_matrix = np.dot(matrix_1, matrix_2)
    return multiplied_matrix.max()

results = [] # Средние знаения
for i in range(100):
    X = np.random.standard_normal((3,3))
    Y = np.random.standard_normal((3,3))
    results.append((mul_matrix_n_max(X,Y)))

arr = np.mean(results) # Средняя от аррея
arr

2.6102748592601857

### Pandas

#### Ответь на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

[Данные](https://www.dropbox.com/s/dvfitn93obn0rql/2008.csv?dl=0) и их [описание](http://stat-computing.org/dataexpo/2009/the-data.html)

In [24]:
import pandas as pd
# %matplotlib inline
df = pd.read_csv('2008.csv')
df

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
0      2008      6          18          3   2111.0        2055   2308.0   
1      2008      6           4          3   1426.0        1410   1730.0   
2      2008      8           3          7   1143.0        1145   1501.0   
3      2008      1          23          3   1141.0        1144   1323.0   
4      2008      5           4          7    815.0         820   1243.0   
5      2008      1           3          4   1349.0        1325   1640.0   
6      2008      3          31          1   1359.0        1400   1413.0   
7      2008      4          22          2   1815.0        1820   2057.0   
8      2008      3           4          2    626.0         630    820.0   
9      2008     10           6          1   1905.0        1907     24.0   
10     2008     11          16          7   2042.0        2000     35.0   
11     2008      3           6          4      NaN        1605      NaN   
12     2008     12          23          2   1101.0        1050   1554.0   
13     2008      7          15          2   1348.0        1355   1522.0   
14     2008      1          29          2   1528.0        1510   1630.0   
15     2008     11          13          4   1651.0        1700   1900.0   
16     2008      7           5          6    557.0         600    918.0   
17     2008      7           8          2   1951.0        1950   2203.0   
18     2008      8          17          7   2005.0        1945    103.0   
19     2008      5           2          5   1044.0        1045   1535.0   
20     2008      5          19          1    906.0         913    927.0   
21     2008      8           2          6    942.0         945   1202.0   
22     2008      1          14          1   1442.0        1445   1601.0   
23     2008      5          19          1   2032.0        2000   2207.0   
24     2008      5          24          6    741.0         745   1052.0   
25     2008      7          19          6    901.0         900   1215.0   
26     2008      9          23          2    752.0         800   1000.0   
27     2008      1          22          2   1639.0        1640   1714.0   
28     2008      3          24          1   1645.0        1645   1930.0   
29     2008      3          24          1    811.0         815    917.0   
...     ...    ...         ...        ...      ...         ...      ...   
69970  2008      7          10          4    937.0         935   1039.0   
69971  2008     12           7          7   2201.0        2150   2328.0   
69972  2008      4           9          3    855.0         845   1603.0   
69973  2008      3          22          6   1303.0        1306   1333.0   
69974  2008      8          19          2   1259.0        1300   1456.0   
69975  2008      4          20          7   1840.0        1810   1929.0   
69976  2008     12          31          3   2011.0        2012   2122.0   
69977  2008      4           6          7    840.0         835   1106.0   
69978  2008     12           9          2    726.0         731      NaN   
69979  2008     12           2          2    908.0         915   1055.0   
69980  2008      5          12          1   1155.0        1140   1419.0   
69981  2008      1           2          3   1122.0        1048   1302.0   
69982  2008      6          13          5   1351.0        1400   1701.0   
69983  2008      9           2          2   1351.0        1355   1352.0   
69984  2008     10           4          6    605.0         615    657.0   
69985  2008     12          11          4    615.0         618    745.0   
69986  2008     12           4          4   1901.0        1905   1952.0   
69987  2008     11          15          6    651.0         659    903.0   
69988  2008     12           7          7   1324.0        1325   1419.0   
69989  2008      7          24          4     28.0          30    550.0   
69990  2008     12          23          2   1627.0        1630   1714.0   
69991  2008      4          24  

**6. ** Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)

In [23]:
df[df['Cancelled'] > 0]

Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  \
11     2008      3           6          4      NaN        1605      NaN   
78     2008      1          19          6      NaN         750      NaN   
103    2008      7          24          4      NaN        1230      NaN   
112    2008      2           4          1      NaN         620      NaN   
128    2008      1          21          1      NaN        1838      NaN   
194    2008      1          28          1      NaN        1640      NaN   
204    2008      6          13          5      NaN        1229      NaN   
236    2008      7          19          6      NaN         544      NaN   
257    2008      4          19          6      NaN        1345      NaN   
267    2008      9          23          2      NaN        1400      NaN   
269    2008      2          17          7      NaN        1345      NaN   
288    2008      9          14          7      NaN        1115      NaN   
352    2008      1          20          7      NaN        2023      NaN   
375    2008     12          22          1      NaN         935      NaN   
423    2008      1          23          3      NaN        1640      NaN   
428    2008     10           3          5      NaN        1229      NaN   
429    2008      3           6          4      NaN        1820      NaN   
430    2008      8           5          2      NaN         810      NaN   
445    2008      2          11          1      NaN         635      NaN   
526    2008     12          30          2      NaN         825      NaN   
554    2008     12          27          6      NaN         700      NaN   
564    2008      9          12          5      NaN        1630      NaN   
572    2008      9          13          6      NaN        1439      NaN   
583    2008      3           3          1      NaN        1745      NaN   
648    2008      1          10          4      NaN        2101      NaN   
675    2008      1          29          2      NaN         700      NaN   
720    2008      6          29          7      NaN        1500      NaN   
721    2008      1          28          1      NaN        1930      NaN   
816    2008      9           3          3      NaN        1440      NaN   
821    2008      8          11          1      NaN          50      NaN   
...     ...    ...         ...        ...      ...         ...      ...   
69037  2008      7          11          5      NaN        1225      NaN   
69045  2008     10          23          4      NaN        1905      NaN   
69046  2008      8          14          4      NaN        1800      NaN   
69108  2008      1          30          3      NaN         720      NaN   
69130  2008      3          18          2      NaN        1425      NaN   
69133  2008      7           1          2      NaN        2024      NaN   
69135  2008      2          22          5      NaN        1820      NaN   
69136  2008      7          10          4      NaN        1510      NaN   
69138  2008      8          15          5      NaN        1755      NaN   
69152  2008      2          25          1      NaN        1735      NaN   
69184  2008      7          13          7      NaN        1119      NaN   
69189  2008      5           9          5      NaN        1400      NaN   
69249  2008      8           4          1      NaN        2055      NaN   
69310  2008      2          22          5      NaN        2030      NaN   
69374  2008      1          16          3      NaN        1959      NaN   
69540  2008      3          19          3      NaN        1635      NaN   
69570  2008     12          17          3      NaN        1030      NaN   
69607  2008      9          26          5      NaN         830      NaN   
69672  2008     12          19          5      NaN        1857      NaN   
69703  2008      7          18          5      NaN        2005      NaN   
69710  2008      7          12          6      NaN        1240      NaN   
69748  2008      1          28  

**7. ** Найди среднее, минимальное и максимальное расстояние, пройденное самолетом.

In [37]:
print(df['Distance'].mean())
print(df['Distance'].max())
print(df['Distance'].min())

724.5082571428571
4962
31


**8. ** Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?

In [85]:
groups = df.groupby('Origin')
airports = groups.groups.keys()

stat = []
for i in airports:
    stat.append([i, len(groups.groups[i])])

airport = ''
maximum = 0
for i in stat:
    if i[1] > maximum:
        maximum = i[1]
        airport = i[0]

print(airport, maximum)
print(stat)
    


ATL 4134
[['ABE', 45], ['ABI', 30], ['ABQ', 408], ['ABY', 7], ['ACK', 5], ['ACT', 24], ['ACV', 34], ['ACY', 2], ['ADK', 1], ['ADQ', 6], ['AEX', 35], ['AGS', 15], ['AKN', 1], ['ALB', 118], ['ALO', 3], ['AMA', 78], ['ANC', 217], ['ASE', 52], ['ATL', 4134], ['ATW', 53], ['AUS', 541], ['AVL', 41], ['AVP', 34], ['AZO', 31], ['BDL', 292], ['BET', 12], ['BFL', 50], ['BGM', 9], ['BGR', 17], ['BHM', 245], ['BIL', 42], ['BIS', 13], ['BLI', 1], ['BMI', 66], ['BNA', 541], ['BOI', 162], ['BOS', 1162], ['BQK', 3], ['BQN', 22], ['BRO', 11], ['BRW', 8], ['BTM', 13], ['BTR', 87], ['BTV', 66], ['BUF', 264], ['BUR', 304], ['BWI', 1032], ['BZN', 43], ['CAE', 102], ['CAK', 92], ['CDC', 8], ['CDV', 16], ['CEC', 14], ['CHA', 48], ['CHO', 9], ['CHS', 136], ['CIC', 9], ['CID', 86], ['CLD', 25], ['CLE', 624], ['CLL', 20], ['CLT', 1250], ['CMH', 331], ['CMI', 29], ['CMX', 4], ['COD', 14], ['COS', 152], ['CPR', 31], ['CRP', 48], ['CRW', 45], ['CSG', 8], ['CVG', 878], ['CWA', 37], ['DAB', 41], ['DAL', 577], ['DAY'